#!/bin/bash
#
# Copyright (C) 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

FILE="$1"
DIR="$(dirname $0)"

if [ -r "$DIR/dci-vault-dump.yml" ]; then
    PLAYBOOK="$DIR/dci-vault-dump.yml"
elif [ -r "$VIRTUAL_ENV/../../dciclient/dci-vault-dump.yml" ]; then
    PLAYBOOK="$VIRTUAL_ENV/../../dciclient/dci-vault-dump.yml"
elif [ -r "$DCI_VAULT_DUMP_YML" ]; then
    PLAYBOOK="$DCI_VAULT_DUMP_YML"
else
    PLAYBOOK=/usr/share/python-dciclient/dci-vault-dump.yml
fi

ansible-playbook --vault-id ${DCI_VAULT_CLIENT:=$(type -p dci-vault-client)} -e "@$FILE" "$PLAYBOOK" | grep '        "'| sed -e s/'        "'// -e 's/\\//g' -e 's/",$//' -e 's/^}"$/}/'|sed -e '/"_msg_":/d'

# dci-vault-dump ends here
